truncate output.
python-discord/sir-lancebot pull request #1041
Opened 2022-02-22 14:00 UTC by MaskDuck

## Relevant Issues

Close #990 

## Description
I have truncated the output using the shorten_output method, limit the output to be 99980* character.
(*) the reason why is it 99980 is there should be 20 charater in the end stating that the output was truncated, they are `\n[output truncated]`

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

2022-02-22 14:39 UTC, Akarys42 requested changes
Just a tiny thing

2022-02-22 14:39 UTC, Akarys42 commented on bot/exts/core/internal_eval/_internal_eval.py
> +        data = self.shorten_output(output, max_length=99980)
`99980` should probably be a constant

2022-02-22 14:45 UTC, MaskDuck commented on bot/exts/core/internal_eval/_internal_eval.py
> +        data = self.shorten_output(output, max_length=99980)
it shouldn't be change?

2022-02-22 16:06 UTC, MaskDuck commented
i mean constant lol

2022-02-25 01:46 UTC, Akarys42 approved these changes

2022-03-03 01:26 UTC, brad90four reviewed
Could this be done instead by setting the default `max_length` value to 99980?

```py
    @staticmethod
    def shorten_output(
            output: str,
            max_length: int = 99980,
            placeholder: str = "\n[output truncated]"
    ) -> str:
```

2022-03-03 02:16 UTC, brad90four approved these changes
~~LGTM, nice and clean 👌 ~~
My suggestion was a bad one, changes will be reverted. [Conversation in dev-contrib](https://discord.com/channels/267624335836053506/635950537262759947/948766129076195338)

2022-03-03 02:38 UTC, MaskDuck commented
@brad90four reverted =)

2022-03-03 02:39 UTC, MaskDuck commented
ok the linter doesnt complain about anything ig

2022-03-03 02:43 UTC, brad90four approved these changes
This definitely works

2022-03-04 08:57 UTC, jb3 approved these changes

2022-03-04 08:58 UTC, merged