Fix: .uwu incorrectly transforms emojis in their raw text form
python-discord/sir-lancebot pull request #1078
Opened 2022-07-12 22:55 UTC by ionite34

## Relevant Issues
Fixes #1072

## Description
6db84b38568d3f53c1b1bec4c66c1c8f2ee7b1ac
- Added pattern `RE_EMOJI` to capture emoji markdowns
- Implemented `Emoji` data class for emoji information and displayability inferencing
- Added function `_ext_emoji_replace` to replace external undisplayable emojis with random emoticons
- Added call to `_ext_emoji_replace` at the end of `_uwuify`

## Fixes / formatting
202d53b3f7ebe4d6041a2e5a4c1419bc16b27e11
- Added type checking annotations for `fun_cog` using `typing.TYPE_CHECKING`

21194a8817ee34229a211f6f5aae8978d054a884
- Replaced a redundant single-letter regex character class with the character itself

## Example
- Built-in emojis and emojis the bot is able to display (due to sharing a server) are returned normally.
- For external undisplayable emojis, the bot correctly replaces it with a random emoticon from the `EMOJIS` list.

![Example](https://cdn.ionite.io/img/aiYZZI.jpg)

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

2022-07-20 23:48 UTC, ChrisLovering requested changes
Just a few small comments, looks good otherwise.

I also really appreciate you including screenshots of it in action in your PR! :)

2022-07-20 23:48 UTC, ChrisLovering commented on bot/exts/fun/uwu.py
> +REGEX_EMOJI = re.compile(r"<(a?)?:(\w+):(\d{18})>?", re.ASCII)
```suggestion
REGEX_EMOJI = re.compile(r"<(a)?:(\w+?):(\d{15,21}?)>", re.ASCII)
```
The `?` inside the first match (a?) is unneeded as the is another ? outside the match block, doing the same thing.

The ID for the emoji is a snowflake, so it's actually valid between 15 and 21 characters.

2022-07-20 23:48 UTC, ChrisLovering commented on bot/exts/fun/uwu.py
> +        """Replaces external emojis with emoticons."""
```suggestion
        """Replaces any emoji the bot cannot send in input_text with a random emoticons."""
```

2022-07-21 00:25 UTC, ChrisLovering approved these changes

2022-08-02 17:00 UTC, wookie184 approved these changes
I don't have nitro so there was a limit to what I could test, but this seems good, thanks!

2022-08-02 17:02 UTC, merged