Added "christmasify" avatar effect command.
python-discord/sir-lancebot pull request #1466
Opened 2024-02-21 13:02 UTC by SockYeh

## Relevant Issues

Closes #937 

## Description

* Added "christmasify" command to add a Christmas touch to user's avatar.
* Currently has 2 effects - Room for future additions
    * Make avatar chilly
    * Add ornaments
## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

2024-02-23 16:55 UTC, wookie184 requested changes
This looks great :)

Where did you get `ice_frame.png` and `ornaments_frame.png` from? We need to make sure they're licensed appropriately so we can use them here. I also wonder if there's a higher quality version of `ice_frame.png`, currently it looks quite blurry.

2024-02-23 16:55 UTC, wookie184 commented on bot/exts/avatar_modification/_effects.py
> +            image = ImageOps.colorize(image.convert("L"), (0, 0, 0), (212, 235, 242))
What is this doing?

2024-02-23 18:37 UTC, SockYeh commented on bot/exts/avatar_modification/_effects.py
> +            image = ImageOps.colorize(image.convert("L"), (0, 0, 0), (212, 235, 242))
it adds a blue hue to the img

2024-02-23 18:37 UTC, SockYeh commented
> This looks great :)
> 
> Where did you get `ice_frame.png` and `ornaments_frame.png` from? We need to make sure they're licensed appropriately so we can use them here. I also wonder if there's a higher quality version of `ice_frame.png`, currently it looks quite blurry.

It was just downloaded from google so i have no clue where the source actually is 😅

2024-02-23 19:14 UTC, SockYeh commented
> > > This looks great :)
> > > Where did you get `ice_frame.png` and `ornaments_frame.png` from? We need to make sure they're licensed appropriately so we can use them here. I also wonder if there's a higher quality version of `ice_frame.png`, currently it looks quite blurry.
> > 
> > 
> > It was just downloaded from google so i have no clue where the source actually is 😅
> 
> Reverse image search for `ornaments_frame.png` led me to [this](https://www.hiclipart.com/free-transparent-background-png-clipart-plegr) (among other similar looking websites). They've mentioned that they do not require attribution for non-commercial uses.
> 
> `ice_frame.png` can be found on freepik.com [here](https://www.freepik.com/free-vector/blue-snowflakes-frame_829245.htm) and they've stated that they require attribution. (Also I do not see a `.png` download option but they do have `.svg`). It seems that the same author has also uploaded the image to [shutterstock](https://www.shutterstock.com/image-vector/snowflake-frame-340281305).

that's great! What is the next step?

2024-04-16 10:56 UTC, wookie184 commented
Ideally we'd use assets that don't require attribution, since that's the easiest option where possible.

For ones that do require attribution, I think it's OK to put it in the command's help text.

2024-04-25 16:55 UTC, SockYeh commented
I am unable to find images so would be grateful if someone could find one to add to the bot. Thanks.

2024-11-23 19:28 UTC, ChrisLovering commented
Once copyright free images have been found, we can look into opening this back up and implementing this change.

2024-11-23 19:28 UTC, closed without merging