feature/add wonder twins command
python-discord/sir-lancebot pull request #524
Opened 2020-11-20 02:52 UTC by fisher60

This commit implements a wonder twins inspired command. This is a purely fun command that uses real transformations from the show to make random new transformations. The yaml is all hand transcribed from the actual show.

## Relevant Issues
Closes: #523 

## Description
I added a wonder_twins cog as well as the yaml of quotes from the show.

## Reasoning
It has been implemented so that users can quickly use the command to get a random, hopefully funny, transformation inspired by the show of the same name.

## Screenshots

![image](https://user-images.githubusercontent.com/39353605/99751811-d9f3e480-2a97-11eb-9ac5-724593cfb913.png)

## Additional Details
`pipenv run lint` changed line endings for many files, I used `pipenv run flake8` instead for linting.

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

2020-11-21 12:53 UTC, ks129 reviewed
Few small suggestions

2020-11-21 12:53 UTC, ks129 commented on bot/exts/evergreen/wonder_twins.py
> +    WATER_TYPES, OBJECTS, ADJECTIVES = info["water_types"], info["objects"], info["adjectives"]
I think it should be better to do this in `__init__` function, as constants is meant to be static, but loading them from file makes them dynamic.

2020-11-21 12:53 UTC, ks129 commented on bot/exts/evergreen/wonder_twins.py
> +        if insert_word[-1] == "s":
I'd prefer here for readability:
```suggestion
        if insert_word.endswith("s"):
```

2020-11-22 01:56 UTC, gustavwilliam requested changes
Thanks for the contribution! I don't know enough about Wonder Twins to understand what these phrases are, but they seem funny. 

This is purely a code review and I'll test the command on a later date.

2020-11-22 01:56 UTC, gustavwilliam commented on bot/exts/evergreen/wonder_twins.py
> +            self.water_types, self.objects, self.adjectives = info["water_types"], info["objects"], info["adjectives"]
```suggestion
            self.water_types, self.objects, self.adjectives = info
```
This looks clearer to me. If you don't like the proposed solution, I think putting it on 3 lines would look the best. The original code had a bit too much going on in that single line, in my opinion.

2020-11-22 01:56 UTC, gustavwilliam commented on bot/exts/evergreen/wonder_twins.py
> +        """Appends one word onto the end of another phrase, used to format the use of 'an' or 'a'."""
I don't fully understand the last part of this docstring. It would be nice with a slightly more straightforward sentence.

2020-11-22 01:56 UTC, gustavwilliam commented on bot/exts/evergreen/wonder_twins.py
> +        words = [object_name, water_type]
What is the purpose of this list?

2020-11-22 23:49 UTC, gustavwilliam approved these changes
Looks good to me. I still haven't been able to test this, but I think it's simple enough that one person testing it would be enough. This seems like a fun command.

2020-11-23 14:53 UTC, ks129 approved these changes
Code looks good. Tested it locally too, ran ~30 times this command and at my level of English, everything looks right.

2020-11-24 04:47 UTC, MarkKoz commented on bot/exts/evergreen/wonder_twins.py
> +            info = yaml.load(f, Loader=yaml.FullLoader)
It's good practice to use `safe_load` but it's okay here since the YAML content is a static resource.

2020-11-24 04:48 UTC, merged