Sentry SDK version bump, integrations adding and Sentry release workflow
python-discord/sir-lancebot pull request #547
Opened 2020-12-19 14:15 UTC by ks129

## Relevant Issues

Approved in #dev-core.

## Description

- Bumped Sentry SDK version from `0.14` to `0.19`.
- Added Redis and aiohttp integrations to Sentry SDK initializing.
- Added workflow for creating Sentry releases (based on site's one).

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

2020-12-19 14:17 UTC, jb3 requested changes
We should really be initialising the Sentry SDK with the release label. I think @lemonsaurus implemented this on site so we should look there for how the SHA is fetched (we can either use a `.git` folder or inject the SHA into the Docker build, I think I prefer the latter) and passed into the Sentry SDK.

2020-12-19 17:22 UTC, jb3 requested changes

2020-12-19 17:22 UTC, jb3 commented on bot/__main__.py
> +    release=f"pydis-sir-lancebot@{GIT_SHA}"
This can just be `sir-lancebot`.
```suggestion
    release=f"sir-lancebot@{GIT_SHA}"
```

2020-12-19 17:22 UTC, jb3 commented on bot/__main__.py
> +        AioHttpIntegration()
We concluded that we do not need the AioHttp integration, it is for servers.
```suggestion
```

2020-12-19 17:56 UTC, jb3 approved these changes

2020-12-20 18:40 UTC, MarkKoz approved these changes

2020-12-20 18:43 UTC, merged