Add http status dog and add http_cat to group http_status
python-discord/sir-lancebot pull request #571
Opened 2021-01-30 23:52 UTC by Shivansh-007

## Relevant Issues

## Description
HTTP status dogs doesn't the following codes: `[101, 102, 421, 511, 499, 599, 415]`.
I have made a group for `cat` and `dog` status codes and dog status code is just duplicate to that of the cat just it adds another check by checking the response status after requesting the url.

## Screenshots
![Screenshot from 2021-01-31 05-19-21](https://user-images.githubusercontent.com/69356296/106370861-45a1da00-6384-11eb-89fa-97c3a2078732.png)
![Screenshot from 2021-01-31 05-19-39](https://user-images.githubusercontent.com/69356296/106370863-476b9d80-6384-11eb-930d-9da43632723c.png)

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

2021-01-31 11:52 UTC, ChrisLovering requested changes
I think we should rename the cog. The two could do's are optional, if you feel like implementing them. If not, they can be raised as separate issues :)

2021-01-31 11:52 UTC, ChrisLovering commented on bot/exts/evergreen/status_codes.py
> +                    raise ValueError
Could do: raise `NotImplementedError` instead, and handle it separately from `ValueError`. This way we inform user if the code doesn't exist at all, or if its just not been implemented by httpstatusdogs.com

2021-01-31 11:52 UTC, ChrisLovering commented on bot/exts/evergreen/status_codes.py
> +class StatusCats(commands.Cog):
Should do: Rename the cog, now that it does more than just cats.

2021-01-31 11:52 UTC, ChrisLovering commented on bot/exts/evergreen/status_codes.py
> +            embed.set_image(url=f'https://http.cat/{code}.jpg')
Could do: `http.cat` raises a 404 on some status codes that `HTTPStatus` says is a valid code, so we could handle those in a similar way to what you have done for the dog command.

2021-02-01 16:43 UTC, ChrisLovering requested changes
Just 1 change outstanding. I've tested the rest of this locally and it seems good to me! Nice job :)

2021-02-01 16:43 UTC, ChrisLovering commented on bot/exts/evergreen/status_codes.py
> +                    raise NotImplementedError
Must do: Add an except block for this raised error, like you have for dogs

2021-02-01 18:56 UTC, Xithrius commented
When you input 101 for the dog status codes, what does it output? A 404?

2021-02-01 20:05 UTC, ChrisLovering commented
> When you input 101 for the dog status codes, what does it output? A 404?

![image](https://user-images.githubusercontent.com/9753350/106511923-d550a100-64c8-11eb-87d2-bb30530c4637.png)

2021-02-01 20:11 UTC, Xithrius commented
Sorry, what I mean is when requesting from the url for a 101, what does it return?

2021-02-01 20:15 UTC, ChrisLovering commented
> Sorry, what I mean is when requesting from the url for a 101, what does it return?

My bad, any code that hasn't been implemented redirects to `https://httpstatusdogs.com/404-not-found` which is a page with a 404 image, but a bunch of other content. This is the case for 101, but also 999 as example.

2021-02-01 20:18 UTC, Xithrius commented
I see, thank you for this information.

2021-02-01 23:54 UTC, Shivansh-007 commented
@ChrisLovering Mentioned the requested changes!

2021-02-01 23:56 UTC, ChrisLovering approved these changes
LGTM!

2021-02-03 20:14 UTC, Xithrius commented on bot/exts/evergreen/status_codes.py
> +    @http_status_group.command(aliases=['cat'])
```suggestion
    @http_status_group.command(name='cat')
```

2021-02-03 20:14 UTC, Xithrius commented on bot/exts/evergreen/status_codes.py
> +    @http_status_group.command(aliases=['dog'])
```suggestion
    @http_status_group.command(name='dog')
```

2021-02-03 20:14 UTC, Xithrius commented on bot/exts/evergreen/status_codes.py
> +                    f'https://httpstatusdogs.com/img/{code}.jpg',
URL should be a constant.

2021-02-03 20:28 UTC, Xithrius commented on bot/exts/evergreen/status_codes.py
> +            await ctx.send(embed=embed)
Good use of the `finally` statement.

2021-02-03 20:29 UTC, Xithrius commented on bot/exts/evergreen/status_codes.py
> +                    embed.set_image(url=f'https://httpstatusdogs.com/img/{code}.jpg')
Once this URL is a constant, you'll only have to only format this once at the start of this function.

2021-02-03 23:54 UTC, Shivansh-007 commented
Mentioned the requested changes @Xithrius !

2021-02-04 00:02 UTC, Xithrius approved these changes

2021-02-04 00:48 UTC, merged