Feature/improve wiki
python-discord/sir-lancebot pull request #600
Opened 2021-02-22 15:18 UTC by Shivansh-007

## Relevant Issues
Closes #565 

## Description
This has been implemented with help of `aiohttp` to request and get json data of the Wikipedia Article. It then filters the data and stores only the required information namely `Title`, `Snippet` and `Page ID`. This filtered data to the Line Paginator.

## Reasoning
Approved by Staff Member.

## Screenshots

### No Result Found

![Screenshot from 2021-02-22 20-35-51](https://user-images.githubusercontent.com/69356296/108727918-0dd71e00-754f-11eb-8a3a-f15b65efc5fa.png)

### Results Found

![Screenshot from 2021-02-22 20-30-28](https://user-images.githubusercontent.com/69356296/108727923-0f084b00-754f-11eb-9851-72bad012e80f.png)

### 1 Result Found

![Screenshot from 2021-02-22 20-32-13](https://user-images.githubusercontent.com/69356296/108728042-2d6e4680-754f-11eb-886e-21d893a87026.png)

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

2021-02-24 18:42 UTC, RohanJnr requested changes
Just picked up some stuff just by glancing through the code, haven't tested a lot yet, will do that soon

2021-02-24 18:42 UTC, RohanJnr commented on bot/exts/evergreen/wikipedia.py
> +                 "/330px-Wikipedia-logo-v2.svg.png"
I think using () to write multiline strings looks better.
```suggestion
SEARCH_API = (
    "https://en.wikipedia.org/w/api.php?action=query&list=search&prop=info&inprop=url&utf8=&"
    "format=json&origin=*&srlimit={number_of_results}&srsearch={string}"
)
WIKI_THUMBNAIL = (
    "https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Wikipedia-logo-v2.svg"
    "/330px-Wikipedia-logo-v2.svg.png"
)
```

2021-02-24 18:42 UTC, RohanJnr commented on bot/exts/evergreen/wikipedia.py
> +    api_issue = "Whoops, the Wikipedia API is having some issues right now. Try again later."
Since both the error message are used only once, they can be directly written in the error handling snippet.

2021-02-24 18:42 UTC, RohanJnr commented on bot/exts/evergreen/wikipedia.py
> +                    return None
```suggestion
                    return
```

2021-02-24 18:42 UTC, RohanJnr commented on bot/exts/evergreen/wikipedia.py
> +                return None
```suggestion
                return
```

2021-02-24 18:42 UTC, RohanJnr commented on bot/exts/evergreen/wikipedia.py
> +        contents = await self.wiki_request(ctx, search)
You can just send the `channel` instead of sending the entire context with `ctx.channel`

2021-02-24 18:45 UTC, RohanJnr commented on bot/exts/evergreen/wikipedia.py
> +                        line = WIKI_SEARCH_RESULT.format(**formatting)
Redundant variable `formatting`
```suggestion
                        line = WIKI_SEARCH_RESULT.format(
                            name=article['title'],
                            description=unescape(
                                re.sub(
                                    WIKI_SNIPPET_REGEX, '', article['snippet']
                                )
                            ),
                            url=f"https://en.wikipedia.org/?curid={article['pageid']}"
                        )
```

2021-02-25 06:45 UTC, RohanJnr approved these changes

2021-03-01 16:34 UTC, Senjan21 approved these changes
Looks good, thanks.

2021-03-01 16:35 UTC, merged