Aoc fixes
python-discord/sir-lancebot pull request #616
Opened 2021-03-08 19:46 UTC by Akarys42

## Relevant Issues

🤷‍♂️ 

## Description

- Replace a dead variable with its actual name
- Restrict the aoc leaderboard commands to December 

## Reasoning

The dead variable caused the cog to not properly unload while the leaderboard cannot work outside of December. 

## Screenshots

*none*

## Additional Details

I mean, do you really need additional details? 

## Did you:

- [no, I don't like them] Join the [**Python Discord Community**](https://discord.gg/python)?
- [no deps] If dependencies have been added or updated, run `pipenv lock`?
- [never lint] **Lint your code** (`pipenv run lint`)?
- [maybe] Set the PR to **allow edits from contributors**?

2021-03-08 21:30 UTC, SebastiaanZ requested changes

2021-03-08 21:30 UTC, SebastiaanZ commented on bot/exts/christmas/advent_of_code/_cog.py
>          self.status_task = None
We could just remove the of initialization of these names here, as we reassign them a few lines lower anyway. I think this is a leftover from a time where they may not have been assigned at `__init__` time.

2021-03-09 11:31 UTC, SebastiaanZ approved these changes

2021-03-09 15:51 UTC, Kronifer commented
Idk man, you didn't lint

2021-03-10 03:11 UTC, Xithrius approved these changes

2021-03-10 03:12 UTC, merged