change ctx.send_help to ctx.invoke(help_command)
python-discord/sir-lancebot pull request #625
Opened 2021-03-11 23:21 UTC by ToxicKidz

;

## Relevant Issues
Closes #624 

## Description
I've changed all the `ctx.send_help`'s to `bot.get_command("help")` and `ctx.invoke(help_command, ctx.command.name)`.

## Reasoning

## Screenshots
Before:
![image](https://user-images.githubusercontent.com/78174417/110868352-708e2080-8296-11eb-9f10-b7da2e781311.png)

After:
![image](https://user-images.githubusercontent.com/78174417/110868437-93203980-8296-11eb-8fd5-38ac60d6c654.png)

## Additional Details
Affected commands are `.games`, `.snakes`, `.space`,  `.emoji`, `.minesweeper`, `.movies`, `.status`, `.extensions` (and its subcommands), and `.bemyvalentine`.

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

2021-03-12 07:53 UTC, Shivansh-007 reviewed
Can we add `help_command` a class attribute in `Bot` class in `bot/bot.py`, then we could just do:
```py
await ctx.invoke(self.bot.help_command, ctx.command.name)
```

2021-03-12 08:45 UTC, anand2312 commented
> Can we add `help_command` a class attribute in `Bot` class in `bot/bot.py`, then we could just do:
> 
> ```python
> await ctx.invoke(self.bot.help_command, ctx.command.name)
> ```

`bot.help_command` is an [attribute of `commands.Bot`](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Bot.help_command)  and has to be of type `HelpCommand`. I don't know how overriding this with something that is not of that type will work.

2021-03-12 08:49 UTC, Shivansh-007 commented
> > Can we add `help_command` a class attribute in `Bot` class in `bot/bot.py`, then we could just do:
> > ```python
> > await ctx.invoke(self.bot.help_command, ctx.command.name)
> > ```
> 
> `bot.help_command` is an [attribute of `commands.Bot`](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Bot.help_command) and has to be of type `HelpCommand`. I don't know how overriding this with something that is not of that type will work.

Ah right! Forgot about the `help_command`, didn't meant to override, what I meant was to add another class attribute to the `Bot` class, so we won't need to do 
```py
help_command = self.bot.get_command("help")
```
everytime we are sending help on a group command.

2021-03-12 13:49 UTC, Akarys42 approved these changes
LGTM, thanks a lot!

2021-03-13 08:10 UTC, ks129 requested changes

2021-03-13 08:10 UTC, ks129 commented on bot/utils/extensions.py
> +async def invoke_help_command(ctx: Context, *commands: str) -> None:
You can receive full name with parents using `ctx.command.qualified_name`, so you don't have to pass command name manually.

2021-03-13 15:20 UTC, ChrisLovering approved these changes
Looks good to me!

2021-03-13 15:43 UTC, ks129 approved these changes

2021-03-13 15:43 UTC, merged