fix: use get_user in 8bitify to avoid events issues
python-discord/sir-lancebot pull request #657
Opened 2021-04-05 14:04 UTC by vcokltfre

## Description
Instead of using the cached user the bot now explicitly fetches the user from the API to get the most up to date profile info

## Reasoning
This is because some API events arent going through on pydis (user_update) and the cached user isnt being updated with a new avatar

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

2021-04-05 14:28 UTC, ToxicKidz requested changes

2021-04-05 14:28 UTC, ToxicKidz commented on bot/exts/evergreen/8bitify.py
> +            author = await self.bot.get_user(ctx.author.id)
`get_user` isn't a coroutine. Did you mean `fetch_user`?

2021-04-05 14:46 UTC, ToxicKidz approved these changes

2021-04-06 20:26 UTC, Xithrius approved these changes

2021-04-06 20:55 UTC, MrKomodoDragon approved these changes
LGTM!

2021-04-06 21:09 UTC, ChrisLovering approved these changes

2021-04-06 21:09 UTC, merged