Use PRDraft emoji when the pr is a draft pr for the .issue|.pr command
python-discord/sir-lancebot pull request #665
Opened 2021-04-08 16:51 UTC by ToxicKidz

## Relevant Issues

Closes #661

## Description

In this PR, I changed the url for getting the pull info to `https://api.github.com/repos/{user}/{repository}/pulls/{number}`, and check if `pull_data["draft"]` is true, and if so, use the :PRDraft: emoji.

## Reasoning

It makes more sense when the PR is a draft that the bot will show the draft PR icon/

## Screenshots

![draft-pr-emoji](https://user-images.githubusercontent.com/78174417/114065539-c55a9200-9868-11eb-86dc-125d2b415436.png)

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

2021-04-08 18:15 UTC, Kronifer approved these changes
Looks good to me! :shipit:

2021-04-08 18:25 UTC, Akarys42 commented
Thabsk for the PR! I'll retarget this PR to #642 to generate conflicts only once :P sorry, you may have to solve some

2021-04-09 16:56 UTC, ChrisLovering approved these changes
Looks good to me, tested locally too.

I also tested the `WonderTwins` and `ConvoStarters` cogs since those are the only ones that use PyYAML (Since this PR upgrades the version to latest)

2021-04-09 17:27 UTC, Akarys42 requested changes
Just an outdated comment

2021-04-09 17:27 UTC, Akarys42 commented on bot/exts/evergreen/issues.py
>                  # When the status is 204 this means that the state of the PR is merged
This comment needs to be updated

2021-04-09 18:00 UTC, merged