feat: add ping command
python-discord/sir-lancebot pull request #681
Opened 2021-04-13 14:48 UTC by vcokltfre

## Relevant Issues
No github issues, but the relevant conversation in pydis/dev-contrib is around here https://discord.com/channels/267624335836053506/635950537262759947/831533475760832603

## Description
A simple command that sends an embed showing the bot's websocket latency. It is simple as was discussed; it has no need to be complex, just provide basic information and more importantly show that the bot is online.

## Screenshots
![image](https://user-images.githubusercontent.com/16879430/114572794-b6f8e580-9c6f-11eb-8fbd-650821e9d4ed.png)

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

2021-04-13 14:50 UTC, ToxicKidz commented on bot/exts/evergreen/ping.py
> +            title="Pong!",
Needs a 🏓

2021-04-13 14:51 UTC, vcokltfre commented
![image](https://user-images.githubusercontent.com/16879430/114573203-148d3200-9c70-11eb-9986-8b5213d53561.png)

2021-04-13 14:53 UTC, ToxicKidz approved these changes
:shipit: :shipit: :shipit:

2021-04-13 14:59 UTC, jb3 requested changes

2021-04-13 14:59 UTC, jb3 commented on bot/exts/evergreen/ping.py
> +            description=f"WS Latency: {round(self.bot.latency * 1000)}ms",
Maybe we use Discord terminology here for clarity.
```suggestion
            description=f"Gateway Latency: {round(self.bot.latency * 1000)}ms",
```

2021-04-13 15:34 UTC, jb3 approved these changes

2021-04-13 20:06 UTC, Kronifer approved these changes
Everything checks out! It's a ping command all right :shipit:

2021-04-14 03:05 UTC, Xithrius approved these changes
Tested, it works well.

2021-04-14 03:06 UTC, merged