Fix errors when a subreddit has <5 posts.
python-discord/sir-lancebot pull request #702
Opened 2021-04-22 19:27 UTC by ChrisLovering

## Relevant Issues

Closes #701

## Description

Changed a list slice from `[1]` to `[0]`.
Added a min check for length of the respond, before shuffling. 

## Reasoning

If a subreddit has <2 posts, the posts[1] check would fail with an IndexError.
If the subreddit had less than 5 posts, then the k=5 check would also error. These changes harden the command for these edge cases.

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

2021-04-22 19:37 UTC, ToxicKidz approved these changes
:shipit:

2021-04-22 19:45 UTC, Kronifer approved these changes
:shipit:

2021-04-23 04:04 UTC, Xithrius requested changes

2021-04-23 04:04 UTC, Xithrius commented on bot/exts/evergreen/reddit.py
>                  "You cannot access this Subreddit as it is ment for those who "
```suggestion
                "You cannot access this Subreddit as it is meant for those who "
```

2021-04-23 13:11 UTC, Xithrius approved these changes
It works well.

2021-04-23 13:21 UTC, merged