Switch from fetch_member to fetch_user in avatar_mod
python-discord/sir-lancebot pull request #725
Opened 2021-05-07 16:37 UTC by ChrisLovering

## Description

This is because discord.py would populate the user portion of the fetched member with cached information which would cause the avatar url not to be updated as we had intended with that function.

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

2021-05-07 16:50 UTC, ToxicKidz requested changes

2021-05-07 16:50 UTC, ToxicKidz commented on bot/exts/evergreen/avatar_modification/avatar_modify.py
> +    async def _fetch_user(self, user_id: int) -> t.Optional[discord.Member]:
```suggestion
    async def _fetch_user(self, user_id: int) -> t.Optional[discord.User]:
```

2021-05-07 17:05 UTC, ToxicKidz approved these changes
Thanks, it works wll! :shipit:

2021-05-10 01:12 UTC, vcokltfre approved these changes
LGTM!

2021-05-10 02:00 UTC, Xithrius approved these changes

2021-05-10 02:00 UTC, merged