Remove superfluous dependencies
python-discord/sir-lancebot pull request #744
Opened 2021-05-17 22:24 UTC by ChrisLovering

## Description

1. Change AoC helpers to use arrow over pytz 
2. remove bs4 and pytz 
3. update arrow to 1.1.0

pytz is only used in one file in the whole bot, so we can remove the dependency by changing AoC to use arrow.  
I chose to use `America/Chicago` arbitrarily, for no other reason that being the first tz google returned that was in EST.

Beautifulsoup4 is no longer used, it used to be used in AoC code a while ago.

I also updated arrow to 1.1.0 while I was here as the breaking changes don't impact us.

## Did you:

- [ ] Join the [**Python Discord Community**](https://discord.gg/python)?
- [ ] Read all the comments in this template?
- [ ] Ensure there is an issue open, or link relevant discord discussions?
- [ ] Read the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

2021-05-17 22:43 UTC, ToxicKidz requested changes
I get this error when I run `.aoc countdown`
```py
05/17/21 18:41:12 - bot.exts.evergreen.error_handler ERROR: Unhandled command error: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
Traceback (most recent call last):
  File "python3.9\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped 
    ret = await coro(*args, **kwargs)
  File "~\sir-lancebot\bot\exts\christmas\advent_of_code\_cog.py", line 103, in aoc_countdown
    datetime_now = datetime.now(_helpers.EST)
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
```

2021-05-17 23:32 UTC, ToxicKidz approved these changes
:shipit:

2021-05-17 23:36 UTC, jb3 commented
> I chose to use America/Chicago arbitrarily, for no other reason that being the first tz google returned that was in EST.

Will this be consistent? Arrow will presumably implement daylight savings for actual locations.

2021-05-18 02:57 UTC, Shivansh-007 commented on bot/exts/christmas/advent_of_code/_helpers.py
> +EST = "America/Chicago"
According to @janine9vn 
> Chicago is CST/CDT. So one hour before EST/EDT

[New York](https://www.zeitverschiebung.net/en/timezone/america--new_york), should be the right timezone.

2021-05-18 08:54 UTC, ChrisLovering commented
> > I chose to use America/Chicago arbitrarily, for no other reason that being the first tz google returned that was in EST.
> 
> Will this be consistent? Arrow will presumably implement daylight savings for actual locations.

Arrow will shift for daylight savings, which I assume is what we want, rather than a static GMT offset.

2021-05-19 06:57 UTC, Shivansh-007 approved these changes
Looks Good To Me! :shipit:

2021-05-19 07:47 UTC, jb3 approved these changes

2021-05-19 07:47 UTC, merged