updating py_topic.yaml
python-discord/sir-lancebot pull request #763
Opened 2021-06-04 17:02 UTC by blankRiot96

## Relevant Issues

## Description

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

2021-06-07 08:00 UTC, kosayoda requested changes
Thanks for the PR, can you please capitalize `Python` and `Python Discord`?

2021-06-07 08:00 UTC, kosayoda commented on bot/resources/evergreen/py_topics.yaml
> +    - What part of python is currently dieing?
```suggestion
```
I'm not a fan of this question, would you mind either rewording it or removing it?

2021-06-07 08:01 UTC, eivl requested changes

2021-06-12 20:35 UTC, Xithrius commented
@blankRiot96 Will you be able to complete the requested changes?

2021-06-16 12:05 UTC, dawnofmidnight requested changes

2021-06-16 12:05 UTC, dawnofmidnight commented on bot/resources/evergreen/py_topics.yaml
> +    - Are you currently a student, or using python professionally?
Mentioning something about hobby programmers would be nice here, as there are many of those.

2021-07-31 08:56 UTC, Xithrius commented
@blankRiot96 will you be able to finish of this PR? If so, please let me know.

2021-07-31 09:36 UTC, blankRiot96 commented
> @blankRiot96 will you be able to finish of this PR? If so, please let me know.

probably not, as i was banned from the server 
do what you want with the questions

2021-07-31 09:47 UTC, Xithrius commented
I see.

2021-07-31 10:06 UTC, Xithrius commented
Being continued in https://github.com/python-discord/sir-lancebot/pull/792.

2021-07-31 10:06 UTC, closed without merging