Fix android codeblock rendering inconsistency
python-discord/sir-lancebot pull request #839
Opened 2021-09-01 11:58 UTC by wookie184

## Relevant Issues

Closes #615 

## Description

Added newlines before and after codeblocks that didn't have them already. From testing it seems they're only technically required before to fix the android rendering issue, but I added them afterwards as well for consistency.
## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

2021-09-01 14:12 UTC, Shivansh-007 requested changes
The following are missing this change:

- https://github.com/python-discord/sir-lancebot/blob/android-codeblock-fix/bot/exts/evergreen/snakes/_utils.py (the egg stages)
- https://github.com/python-discord/sir-lancebot/blob/a4351738cc074f42b60521c122e8712888c50498/bot/exts/evergreen/cheatsheet.py#L73
- https://github.com/python-discord/sir-lancebot/blob/a4351738cc074f42b60521c122e8712888c50498/bot/exts/evergreen/cheatsheet.py#L67

2021-09-01 14:47 UTC, wookie184 commented
For the eggs I don't think there should have been any leading whitespace so I removed that too.

2021-09-01 14:50 UTC, Shivansh-007 approved these changes

2021-09-02 18:34 UTC, ChrisLovering approved these changes
:shipit:

2021-09-03 07:30 UTC, Xithrius approved these changes

2021-09-03 07:31 UTC, merged