Emoji: make the datetimes offset-naive
python-discord/sir-lancebot pull request #877
Opened 2021-09-20 15:20 UTC by Akarys42

You know the drill, due to discord.py 2.0a0 datetimes are now offset-aware, breaking some code.

Closes python-discord/sir-lancebot#875

2021-09-20 15:21 UTC, ChrisLovering approved these changes

2021-09-20 18:31 UTC, wookie184 requested changes
I think we'd have the same problem here, correct me if i'm wrong
 https://github.com/python-discord/sir-lancebot/blob/8a410f3abd39a1b48c514d32651a50d4bdced492/bot/exts/events/hacktoberfest/hacktober-issue-finder.py#L55-L58

2021-09-21 07:22 UTC, Akarys42 commented
> I think we'd have the same problem here, correct me if i'm wrong
> https://github.com/python-discord/sir-lancebot/blob/8a410f3abd39a1b48c514d32651a50d4bdced492/bot/exts/events/hacktoberfest/hacktober-issue-finder.py#L55-L58

Indeed, it is a bit of a kaizen change but who cares. Changed in 24e099e.

2021-09-21 11:23 UTC, wookie184 requested changes
Just noticed it for the hacktoberissues bit it also needs to be changed here, line 89
```python
            if option == "beginner":
                self.cache_beginner = data
                self.cache_timer_beginner = ctx.message.created_at
            else:
                self.cache_normal = data
                self.cache_timer_normal = ctx.message.created_at
  ```
  Tested after that change and seems to work so that should be all. Alternatively I guess the original datetime set in the `__init__` could have been changed so it is timezone aware, idk what is good or bad though and haven't tried it.

2021-10-03 12:32 UTC, wookie184 approved these changes

2021-10-03 12:34 UTC, merged