Limit user reactions on embed pagination
python-discord/sir-lancebot pull request #936
Opened 2021-11-02 12:02 UTC by Nipa-Code

## Relevant Issues

Close #933 

## Description

I added `restrict_to_user=ctx.author` to wikipedia.py. Limits user reactions to prevent non-author from removing message by adding user restriction to paginator.

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

2021-11-04 16:07 UTC, ChrisLovering requested changes

2021-11-04 16:07 UTC, ChrisLovering commented on bot/exts/utilities/wikipedia.py
> +                contents, ctx, embed, restrict_to_user=ctx.author
This works well, but doesn't need to be split up like this. I'm aware you didn't do this yourself, but lets make it better while we're here. The style we currently go with is this

`await LinePaginator.paginate(contents, ctx, embed, restrict_to_user=ctx.author)`

2021-11-05 10:48 UTC, hedyhli approved these changes

2021-11-05 10:48 UTC, ChrisLovering approved these changes

2021-11-05 10:49 UTC, merged