Interaction tic tac toe
python-discord/sir-lancebot pull request #982
Opened 2021-12-17 22:58 UTC by onerandomusername

## Relevant Issues

closes GH-976

## Description

switched to using interactions for tic tac toe

*start of game*
![image](https://user-images.githubusercontent.com/71233171/146617190-a0746cc2-6fbe-4a9a-9fec-faeb85551c9f.png)

*in progress*
![image](https://user-images.githubusercontent.com/71233171/146617302-169faf08-9e17-4f20-9b57-91853796bcf7.png)

*game over*
![image](https://user-images.githubusercontent.com/71233171/146617126-d6befa07-5fb4-4c67-bce9-9712b55dcbaa.png)

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] Read all the comments in this template?
- [x] Ensure there is an issue open, or link relevant discord discussions?
- [x] Read and agree to the [contributing guidelines](https://pythondiscord.com/pages/contributing/contributing-guidelines/)?

2022-01-02 21:08 UTC, decorator-factory requested changes

2022-01-02 21:08 UTC, decorator-factory commented on bot/exts/fun/tic_tac_toe.py
> +    async def get_move(board: dict[int, str], msg: discord.Message) -> tuple[bool, int, None]:
Does the interface really has to be the same?
You're already checking if the player is an `AI` or a `Player`. So maybe just do something like:
```py
if isinstance(self.current, AI):
    pos = await self.current.get_move(self.board, board)
    interaction = None
else:
    move = await self.current.get_mode(self.board, board)
    if move is None:
        # handle timeout
    pos, inter = move
```

2022-01-02 21:08 UTC, decorator-factory commented on bot/exts/fun/tic_tac_toe.py
>      async def play(self) -> None:
I don't have any concrete suggestions here, but this method is pretty complicated. I don't understand how the game logic works

2022-06-17 03:38 UTC, Xithrius commented
@onerandomusername will you be completing this PR?

2022-08-18 23:07 UTC, Xithrius commented
I'll be closing this PR due to staleness. If this PR is going to be completed, please ping me, along with re-opening.

2022-08-18 23:07 UTC, closed without merging